var acronyms = {
"ITPHR": "Inside-the-park home run:hits on which the batter successfully touched all four bases, without the contribution of a fielding error or the ball going outside the ball park.",
"pNERD": "Pitcher&#39;s NERD: expected aesthetic pleasure of watching an individual pitcher",
"RISP": "Runner In Scoring Position: a breakdown of the batter&#39;s batting average with runners in scoring position, which include runners at second and third bases.",
"SBA/ATT": "Stolen base attempts: total number of times the player has attempted to steal a base (SB+CS)",
"VORP": "Value over replacement player: a statistic that calculates a player&#39;s overall value in comparison to a &#39;replacement-level&#39; player. There are separate formulas for players and pitchers",
"WHIP": "Walks and hits per inning pitched: average number of walks and hits allowed by the pitcher per inning",
"PA/SO": "Plate appearances per strikeout: number of times a batter strikes out to their plate appearance",
"LOB%": "Left on base percentage: LOB% represents the percentage of baserunners a pitcher does not allow to score. LOB% tends to regress toward 70–72% over time, so unusually high or low percentages could indicate that pitcher&#39;s ERA could be expected to rise or lower in the future. An occasional exception to this logic is a pitcher with a very high strikeout rate.",
"IP/GS": "Average number of innings pitched per game",
"FPOM": "First Pitch Outs Made: Number of outs earned where the batter ground or flies out on the first pitch.",
"GIDP": "Double Plays Induced: number of double play groundouts induced",
"GO/AO": "Ground ball fly ball ratio: number of ground ball outs divided by number of fly ball outs",
"DICE": "Defense-Independent Component ERA: an estimate of a pitcher&#39;s ERA based upon the defense-independent components of his statistical line (K, HR, BB, HBP)",
"AB/HR": "At bats per home run: at bats divided by home runs.",
"CERA": "Component ERA: an estimate of a pitcher&#39;s ERA based upon the individual components of his statistical line (K, H, 2B, 3B, HR, BB, HBP)",
"BABIP": "Batting average on balls in play: frequency at which a batter reaches a base after putting the ball in the field of play. Also a pitching category.",
"BB/K": "Walk-to-strikeout ratio: number of bases on balls divided by number of strikeouts",
"AVG": "Batting average (also abbreviated BA): hits divided by at bats (H/AB)",
"BsR": "Base Runs: Another run estimator, like Runs Created; a favorite of writer Tom Tango",
"EQA": "Equivalent average: a player&#39;s batting average absent park and league factors",
"ERA": "Earned run average: total number of earned runs, multiplied by 9, divided by innings pitched",
"ERA+": "Adjusted ERA: earned run average adjusted for the ballpark and the league average",
"XBH": "Extra base hits: total hits greater than singles (2B + 3B + HR)",
"xFIP": "This variant substitutes a pitcher&#39;s own home run percentage with the league average",
"WAR": "Wins above replacement: a non-standard formula to calculate the number of wins a player contributes to his team over a &#39;replacement-level player&#39;",
"FIP": "Fielding independent pitching: a metric, scaled to resemble an ERA, that focuses on events within the pitcher&#39;s control: home runs, walks, and strikeouts",
"G/F": "Ground ball fly ball ratio: ground balls allowed divided by fly balls allowed",
"GDP": "Ground into double play: number of ground balls hit that became double plays",
"GPA": "Gross Production Average: 1.8 times on-base percentage plus slugging percentage, divided by four",
"HBP": "Hit by pitch: times touched by a pitch and awarded first base as a result",
"HLD": "Hold: number of games entered in a save situation, recorded at least one out, did not surrender the lead, and did not complete the game",
"HRA": "Home runs allowed: total home runs allowed",
"IBB": "Intentional base on balls: times awarded first base on balls deliberately thrown by the pitcher. Also known as IW (intentional walk).",
"IRA": "Inherited runs allowed: number of inherited runners allowed to score",
"ISO": "Isolated power: a hitter&#39;s ability to hit for extra bases, calculated by subtracting batting average from slugging percentage",
"K/9": "Strikeouts per nine innings: strikeouts times nine divided by innings pitched (Strikeouts per 9 innings pitched)",
"INN": "Innings: number of innings that a player is at one certain position",
"LOB": "Left on base: number of runners neither out nor scored at the end of an inning.",
"K/BB": "Strikeout-to-walk ratio: number of strikeouts divided by number of base on balls",
"OBA": "Opponents batting average: hits allowed divided by at-bats faced",
"OBP": "On base percentage: times reached base (H + BB + HBP) divided by at bats plus walks plus hit by pitch plus sacrifice flies (AB + BB + HBP + SF).",
"OPS": "On-base plus slugging: on-base percentage plus slugging average",
"PFR": "Power finesse ratio: The sum of strikeouts and walks divided by innings pitched.",
"PIT": "Pitches thrown (Pitch count)",
"RRA": "Relief Run Average: A function of how many inherited base runners a relief pitcher allowed to score.",
"RBI": "Run batted in: number of runners who score due to a batter&#39;s action, except when batter grounded into double play or reached on an error",
"SB%": "Stolen base percentage: the percentage of bases stolen successfully. (SB) divided by (SBA)(stolen bases attempted).",
"SHO": "Shutout: number of complete games pitched with no runs allowed",
"SLG": "Slugging average: total bases achieved on hits divided by at-bats (TB/AB)",
"SVO": "Save opportunity: When a pitcher 1) enters the game with a lead of three or fewer runs and pitches at least one inning, 2) enters the game with the potential tying run on base, at bat, or on deck, or 3) pitches three or more innings with a lead and is credited with a save by the official scorer",
"TOB": "Times on base: times reaching base as a result of hits, walks, and hit-by-pitches (H + BB + HBP)",
"UBR": "Ultimate base running: a metric that assigns linear weights to every individual baserunning event in order to measure the impact of a player&#39;s baserunning skill",
"UZR": "Ultimate zone rating: the ability of a player to defend an assigned &#39;zone&#39; of the field compared to an average defensive player at his position",
"1B": "Single: hits on which the batter reaches first base safely without the contribution of a fielding error.",
"2B": "Double: hits on which the batter reaches second base safely without the contribution of a fielding error.",
"3B": "Triple: hits on which the batter reaches third base safely without the contribution of a fielding error.",
"AB": "At bat: Plate appearances, not including bases on balls, being hit by pitch, sacrifices, interference, or obstruction.",
"BA": "Batting average (also abbreviated AVG): hits divided by at bats (H/AB)",
"BB": "Base on balls (also called a walk): hitter not swinging at four pitches called out of the strike zone and awarded first base.",
"BF": "Total batters faced: opponent team&#39;s total plate appearances",
"BK": "Balk: number of times pitcher commits an illegal pitching action while in contact with the pitching rubber as judged by umpire, resulting in baserunners advancing one base",
"BS": "Blown save: number of times entering the game in a save situation, and being charged the run (earned or not) which eliminates his team&#39;s lead",
"CG": "Complete game: number of games where player was the only pitcher for his team",
"CI": "Catcher&#39;s Interference (e.g., catcher makes contact with bat)",
"CS": "Caught stealing: times tagged out while attempting to steal a base",
"DI": "Defensive Indifference: if the catcher does not attempt to throw out a runner (usually because the base would be insignificant), the runner is not awarded a steal. Scored as a fielder&#39;s choice.",
"DP": "Double plays: one for each double play during which the fielder recorded a putout or an assist.",
"ER": "Earned run: number of runs that did not occur as a result of errors or passed balls",
"FC": "Fielder&#39;s choice: times reaching base safely because a fielder chose to try for an out on another runner",
"FP": "Fielding percentage: total plays (chances minus errors) divided by the number of total chances",
"GB": "Games behind: number of games a team is behind the division leader",
"GF": "Games finished: number of games pitched where player was the final pitcher for his team as a relief pitcher",
"GS": "Games started: number of games a player starts",
"H/9": "Hits per nine innings: hits allowed times nine divided by innings pitched (also known as H/9IP), hits allowed per 9 innings pitched)",
"HB": "Hit batsman: times hit a batter with pitch, allowing runner to advance to first base",
"HR": "Home runs: hits on which the batter successfully touched all four bases, without the contribution of a fielding error.",
"IP": "Innings pitched: number of outs recorded while pitching divided by three",
"IR": "Inherited runners: number of runners on base when the pitcher enters the game",
"PA": "Plate appearance: number of completed batting appearances",
"PB": "Passed ball: charged to the catcher when the ball is dropped and one or more runners advance",
"PO": "Putout: number of times the fielder tags, forces, or appeals a runner and he is called out as a result",
"QS": "Quality start: a game in which a starting pitcher completes at least six innings and permits no more than three earned runs",
"RA": "Run average: number of runs allowed times nine divided by innings pitched",
"RC": "Runs created: statistic that attempts to measure how many runs a player has contributed to his team",
"RF": "Range factor: 9*(putouts + assists)/innings played. Used to determine the amount of field that the player can cover",
"RP": "Runs produced: statistic that attempts to measure how many runs a player has contributed",
"SB": "Stolen base: number of bases advanced by the runner while the ball is in the possession of the defense.",
"SF": "Sacrifice fly: Fly balls hit to the outfield which although caught for an out, allow a baserunner to advance",
"SH": "Sacrifice hit: number of sacrifice bunts which allow runners to advance on the basepaths",
"SO": "Strikeout Also may be notated as &#39;K&#39;",
"SV": "Save: number of games where the pitcher enters a game led by the pitcher&#39;s team, finishes the game without surrendering the lead, is not the winning pitcher, and either (a) the lead was three runs or fewer when the pitcher entered the game; (b) the potential tying run was on base, at bat, or on deck; or (c) the pitcher pitched three or more innings",
"TA": "Total average: total bases, plus walks, plus hit by pitch, plus steals, minus caught stealing divided by at bats, minus hits, plus caught stealing, plus grounded into double plays [(TB + BB + HBP + SB - CS)/(AB - H + CS + GIDP)]",
"TB": "Total bases: one for each single, two for each double, three for each triple, and four for each home run [H + 2B + (2 * 3B) + (3 * HR)] or [1B + (2 * 2B) + (3 * 3B) + (4 * HR)]",
"TC": "Total chances: assists plus putouts plus errors",
"TP": "Triple play: one for each triple play during which the fielder recorded a putout or an assist",
"WP": "Wild pitches: charged when a pitch is too high, low, or wide of home plate for the catcher to field, thereby allowing one or more runners to advance or score",
"XR": "Extrapolated Runs: A linear run estimator developed by Jim Furtado",
"A": "Assists: number of outs recorded on a play where a fielder touched the ball, except if such touching is the putout",
"E": "Errors: number of times a fielder fails to make a play he should have made with common effort, and the offense benefits as a result",
"G": "Games played: number of games where the player played, in whole or in part",
"H": "Hits: times reached base because of a batted, fair ball without error by the defense (for pitchers: Hits allowed)",
"K": "Strike out (also abbreviated SO): number of times that a third strike is taken or swung at and missed, or bunted foul. Catcher must catch the third strike or batter may attempt to run to first base.",
"L": "Loss: number of games where pitcher was pitching while the opposing team took the lead, never lost the lead, and went on to win",
"R": "Runs scored: number of times a player crosses home plate",
"W": "Win: number of games where pitcher was pitching while his team took the lead and went on to win, also the starter needs to pitch at least 5 innings of work (also related: winning percentage)",
};

var str = document.body.innerHTML;
var repl = str.replace(/([A-Z0-9][\w\/%]{0,4}(\+)*)/g, function(match) {
   	if (match in acronyms) {
   		return "<abbr title='" + acronyms[match] + "''>" + match + "</abbr>";
   	}
   	else {
   		return match;
   	}
});

document.body.innerHTML = repl;
